version: 2.1

steps: &steps
    working_directory: /s.el
    steps:
      - run: apt update && apt install -y git ssh make
      - checkout

      - run:
          name: Hello
          command: |
            echo "Hello, world"

jobs:
    emacs-27:
      docker:
        - image: silex/emacs:27.1
      <<: *steps
    emacs-26:
      docker:
        - image: silex/emacs:26.3
      <<: *steps
    emacs-25:
      docker:
        - image: silex/emacs:25.3
      <<: *steps
    emacs-24:
      docker:
        - image: silex/emacs:24.2
      <<: *steps

workflows:
    version: 2.1
    build:
      jobs:
        - emacs-24
        - emacs-25
        - emacs-26
        - emacs-27
